name: aff
description: A Flutter Framework.
version: 0.1.1
author: erkan maraş
homepage:

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.1.8
  device_info: ^0.4.2+7
  package_info: ^0.4.3
  clock: ^1.0.1
  collection: ^1.14.13
  provider: ^4.3.2+2
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.10+1
  test: ^1.14.3
  mockito: ^4.1.1


flutter:
  assets:
    - assets/images/
      
  fonts:
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/fonts/MaterialCommunityIcons.ttf
  # fonts:
  #   - family: OpenSans
  #     fonts: 
  #       - asset: assets/fonts/opensans/OpenSans-Bold.ttf
  #       ...
  #       ... 
  uses-material-design: true
 
 